version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - wp_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
  wordpress:
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network
    depends_on:
      - mariadb
  mariadb:
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp_network

networks:
  wp_network:
    driver: bridge

volumes:
  wordpress_data:
    name: wordpress_data
  mariadb_data:
    name: mariadb_data