version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - wp_network
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - wordpress
  wordpress:
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    expose:
        - "9000"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network

    restart: always
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    image : mariadb:1.1
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp_network
    restart: always

networks:
  wp_network:
    driver: bridge

volumes:
  wordpress_data:
    name: wordpress_data
    driver_opts:
      device: /home/yamajid/data/wordpress_data
      o: bind
      type: none
  mariadb_data:
    name: mariadb_data
    driver_opts:
      device: /home/yamajid/data/mariadb_data
      o: bind
      type: none